### ISSUE TITLE
Consider E-VPN Support

### ISSUE THREAD

**Issue by oscargdd** [oscargdd/l2nm#1]
Consider E-VPN Support (note this is a network model, not the device model to configure E-VPN)

**Comment by billwuqin** [comment]
One of EVPN flavor we can consider support is EVPN data center interconnection. In this flavor, we use  (EVPN) as the control plane for EVPN Overlay networks, where VXLAN , NVGRE  or MPLS over GRE can be used as possible data plane encapsulation options. To model this, we should define peer address, peer protocol

**Comment by billwuqin** [comment]
For EVPN, a few parameters can be considered
1. support enabling or disabling Remote FRR  on the remote PE, 
2.  In case of dual-active scenarios, i.e., a local CE is dual-homed to two local PEs, support Enabling fast reroute (FRR) for MAC routes between the local and remote ends in an EVPN instance.
3. support SR Best effort, SR TE or hybrid mode
4. Isolate Spoken support, i.e., configure the forwarding isolation function to forbid the users bound to the same EVPN instance from accessing each other
5. Configure diffserv mode, service class, color for EVPN instance

**Comment by billwuqin** [comment]
For EVPN bridge domain instance, the following parameters can be considered:
1.Split Horizon support, isolate member interfaces that do not need to communicate
2.Statistics collection,e.g., enable the function of collecting statistics about BUM packets in a BD.
3.Discard Broadcast support
4.Discard Unknown Multicast
5.Discard Unknown Unicast
6. MAC address learning support
7. MAC flapping prevention

**Comment by sbarguil** [comment]
EVPN type nowadays has a address-family support based on vpn-common:address. 

```
                 |  +--rw evpn-bgp
                . . .
                 |  |  +--rw address-family?      **vpn-common:address-family**
```

Do we need to consider other Address-Family type in common yang, for this type of services? Or We defined directly on the L2NM?

**Comment by oscargdd** [comment]
close issue as all the issues are done in lxnm repository.
