### ISSUE TITLE
Add examples to clafify multi-domain scenarios

### ISSUE THREAD

**Issue by oscargdd** [oscargdd/l2nm#11]
In the last OPSAWG meeting there ware the following comments can hierarchical
VPN be supported in this SM? Oscar: Yes, but more review is needed to see if it
is fully supportable Zhenbin Li: Inter-AS scenario? 

The proposal is to add examples in the draft to explain the usage in both scenarios.

**Comment by rgaglian** [comment]
Hi Oscar, I think we need to add examples in general.

**Comment by boucadair** [comment]
To be added into an appendix

**Comment by oscargdd** [comment]
examples sent by roque, upload to git and review

**Comment by oscargdd** [comment]
text and formatting to be provided

**Comment by sbarguil** [comment]
Add examples to clafify multi-domain scenarios IETF-OPSAWG-WG/lxnm#232
