### ISSUE TITLE
EVPN: Vpws-evpn IDs missing

### ISSUE THREAD

**Issue by rgaglian** [oscargdd/l2nm#19]
EVI ID, EVI Source, EVI Target Needed for configuration. All Integer values. Could be received northbound or via a pool.

**Comment by billwuqin** [comment]
We use different name for EVI source and EVI Target.

**Comment by sbarguil** [comment]
EVPN: Vpws-evpn IDs missing IETF-OPSAWG-WG/lxnm#233
