### ISSUE TITLE
EVPN: Add support for dot1q push/pop/translate options

### ISSUE THREAD

**Issue by rgaglian** [oscargdd/l2nm#22]
Missing the option to re-write dot1q information received in access.

**Comment by billwuqin** [comment]
Should we see this as network level parameter or device level configuration parameters? Can we generate these parameters in the device level model during YANG to YANG translation?

**Comment by oscargdd** [comment]
let's keep the issue open, see the use case, and if needed, align and reuse from ccamp.

**Comment by sbarguil** [comment]
EVPN: Add support for dot1q push/pop/translate options IETF-OPSAWG-WG/lxnm#236
