### ISSUE TITLE
EVPN: t-ldp with static label

### ISSUE THREAD

**Issue by rgaglian** [oscargdd/l2nm#23]
When using t-ldp as type, we are missing the mpls-label in the ac-pw-list.

**Comment by oscargdd** [comment]
The question is if the need is to set up the label, and if so, would it be ok to do the same as in the case of RT/RD (auto asign vs explicit assign)

**Comment by sbarguil** [comment]
EVPN: t-ldp with static label IETF-OPSAWG-WG/lxnm#237
