### ISSUE TITLE
EVPN: Incorrect XPATH in when expressions

### ISSUE THREAD

**Issue by rgaglian** [oscargdd/l2nm#24]
Under list signaling-options
container l2vpn-bgp
Existing: when "/l2vpn-ntw/vpn-services/vpn-service/vpn-nodes/vpn-node/signaling-options/type = 'vpn-common:l2vpn-bgp'"
Correct clause: when "../type = 'vpn-common:l2vpn-bgp'"     
 
container evpn-bgp
Existing: when "/l2vpn-ntw/vpn-services/vpn-service/vpn-nodes/vpn-node/signaling-options/type = 'vpn-common:evpn-bgp'"
Correct clause: when "../type = 'vpn-common:evpn-bgp'"
 
container t-ldp-pwe
Existing: when "/l2vpn-ntw/vpn-services/vpn-service/vpn-nodes/vpn-node/signaling-options/type = 'vpn-common:t-ldp'"
Correct clause: when "../type = 'vpn-common:t-ldp'"
 
container l2tp-pwe
Existing: when "/l2vpn-ntw/vpn-services/vpn-service/vpn-nodes/vpn-node/signaling-options/type = 'vpn-common:l2tp'" 
Correct clause: when "../type = 'vpn-common:l2tp'"

**Comment by boucadair** [comment]
Fixed in https://github.com/IETF-OPSAWG-WG/l3nm/commit/c0ec7b9be0c6704795d93d7c49fe6401b38f3eca
