### ISSUE TITLE
EVPN: Missing validation for dot1q

### ISSUE THREAD

**Issue by rgaglian** [oscargdd/l2nm#25]
The following MUST statements are missing.

r.

  deviation "/l2vpn-ntw:l2vpn-ntw/l2vpn-ntw:vpn-services/l2vpn-ntw:vpn-service/l2vpn-ntw:vpn-nodes/l2vpn-ntw:vpn-node/l2vpn-ntw:vpn-network-accesses/l2vpn-ntw:vpn-network-access/l2vpn-ntw:connection/l2vpn-ntw:dot1q-interface/l2vpn-ntw:dot1q/l2vpn-ntw:c-vlan-id" {
    deviate add {
      must "../../../l2vpn-ntw:encapsulation-type='vpn-common:dot1q'"{
        error-message "c-vlan-id can only be set when encapsulation-type is 'vpn-common:dot1q'";
      }
  deviation "/l2vpn-ntw:l2vpn-ntw/l2vpn-ntw:vpn-services/l2vpn-ntw:vpn-service/l2vpn-ntw:vpn-nodes/l2vpn-ntw:vpn-node/l2vpn-ntw:vpn-network-accesses/l2vpn-ntw:vpn-network-access/l2vpn-ntw:connection/l2vpn-ntw:dot1q-interface/l2vpn-ntw:dot1q" {
    deviate add {
      must "../../l2vpn-ntw:encapsulation-type='vpn-common:dot1q' and l2vpn-ntw:c-vlan-id"{
        error-message "c-vlan-id is required when encapsulation-type is 'vpn-common:dot1q'";
      }

**Comment by oscargdd** [comment]
ok, it is reasonable to add it. Qin can take care of creating a pr with the change

**Comment by sbarguil** [comment]
EVPN: Missing validation for dot1q IETF-OPSAWG-WG/lxnm#238
