### ISSUE TITLE
Node list: Limit elements for Point-to-point services

### ISSUE THREAD

**Issue by rgaglian** [oscargdd/l2nm#26]
In point-to-point services, there should be a max of 2 nodes defined in the node list.

**Comment by billwuqin** [comment]
Have a second thought, I am not sure we should add limit to the elements for point to point service.
There are multiple cases we can consider:
1. One PE connect to two ports, the the max-elements and min-elements can be set to 1
2. Two PEs connect to each other with each having one port, the max-elements and min-elements can be set to 2
3. Two local PEs are multihomed connecting the same remote PE, each PE having one port,the max-elements and min-elements can be set to 3
4. Two local PEs are dualhomed connecting to two remote PEs in full mesh, two remote PEs are also dual homed, in this case, ,the max-elements and min-elements can be set to 4

**Comment by oscargdd** [comment]
Even for point to point there could be cases with more that two nodes, hence it is better to avoid the "artificial" limit. Roque, please check if you agree and we can close the issue.

**Comment by sbarguil** [comment]
Node list: Limit elements for Point-to-point services IETF-OPSAWG-WG/lxnm#239
