### ISSUE TITLE
ALMP plus filter policies

### ISSUE THREAD

**Issue by rarco** [oscargdd/l2nm#27]
Possibility to add filter + ALMP at interface level

         sap lag-3:720 create 
            auto-learn-mac-protect
            ingress filter mac 720

configure filter mac-filter 720 create
            default-action forward
            entry 10 create
                description "VRRP"
                match  src-mac 00:00:5e:00:01:00 ff:ff:ff:ff:ff:00
                action drop
            exit

**Comment by oscargdd** [comment]
Double check common module for the mac filter

**Comment by oscargdd** [comment]
The MAC filtering can also apply to L3 VPN cases

**Comment by sbarguil** [comment]
ALMP plus filter policies IETF-OPSAWG-WG/lxnm#240
