### ISSUE TITLE
ECMP configuration for Aliasing

### ISSUE THREAD

**Issue by rarco** [oscargdd/l2nm#28]
Flexibility to allow aliasing to MultiHoming CE

         bgp-evpn
            local-ac-name "MH“ eth-tag 710
            remote-ac-name "HL4-5“ eth-tag 710
            evi 710
            mpls
                    auto-bind-tunnel
                        …
                    exit
                    ecmp 2
                    no shutdown
            exit
         exit

**Comment by oscargdd** [comment]
ECMP support to be added to the draft
In l2nm we have access priority. can it be reused?

**Comment by rarco** [comment]
Don't think so, it should be defined at vpn-service level IMHO.

**Comment by oscargdd** [comment]
Could be called "load balancing"

**Comment by rarco** [comment]
After a double check I think it is better to not include a especific command. The reception of the aliasing label by the remote PE should be enough to enable the load balancing.
