### ISSUE TITLE
Underlying tunnel selection per service/Node

### ISSUE THREAD

**Issue by mlopezm1** [oscargdd/l2nm#3]
In our proposal, There will be an ordered list by priorities of tunnel selection type (i.e.LDP,RSVP-TE, SR, SR-TE,etc..) per node and per services.
The reasonn why this list of preferences must consider also services and not only ingress node is because for services initiated in the same PE router,  one service can be Best Effort and LDP is enough but other service can be low latency and TE is required.
If the Node does not support the first option in the list of preferences then try the second one and so on...

**Comment by oscargdd** [comment]
Currently only one value is posible. Need to add a list. Need to choose how to implement the order. Possibilities: add a "preference/priority", or add a "ordered-by" statement in the list. Suggestions, comments?

**Comment by boucadair** [comment]
Fixed now in #8

**Comment by oscargdd** [comment]
Solved in a5ae5789be7ef8c2173ecfcb577dd8ddd123aaba
