### ISSUE TITLE
Mac Duplication

### ISSUE THREAD

**Issue by rarco** [oscargdd/l2nm#31]
Enabled/Disabled

**Comment by oscargdd** [comment]
Define Frequency, Retry (coming from issue #30 )

**Comment by rarco** [comment]
Frequency=num_moves, Window in minutes and retry also in minutes

**Comment by oscargdd** [comment]
checking if window time is standard or proprietary

**Comment by boucadair** [comment]
Raul to propose the change (including the window timer)

**Comment by rarco** [comment]
Currently mac-loop-prevention is defined at vpn-network-access but it make more sense to me at vpn-service level.

Adding window (timer) to the already present mac-loop-prevention group:
                       +--rw mac-loop-prevention
                       |  +--rw frequency?         uint32
                       |  +--rw protection-type?   identityref
                       **_|  +--rw window?    uint32_**
                       |  +--rw number-retries?    uint32

**Comment by billwuqin** [comment]
We use detect-cycle  in our CLI, which is similar to window proposed by Rarco.

**Comment by sbarguil** [comment]
Mac Duplication IETF-OPSAWG-WG/lxnm#241
