### ISSUE TITLE
Max Neighbour Mac address limit

### ISSUE THREAD

**Issue by rarco** [oscargdd/l2nm#32]

**Comment by oscargdd** [comment]
double check in the model (we think it is covered)

**Comment by oscargdd** [comment]
threshold can be a good option too

**Comment by oscargdd** [comment]
now, it is covered in /l2vpn-ntw/vpn-services/vpn-service/vpn-nodes/vpn-node/vpn-network-accesses/vpn-network-access/mac-addr-limit/mac-num-limit

**Comment by oscargdd** [comment]
do we need to model the behaviour of the noifications when the threshold is crossed? (same would apply for other parameters).

**Comment by oscargdd** [comment]
The model already supports three actions. The parameter is supported at interface level.

**Comment by oscargdd** [comment]
The specific alarm/notification could go to the VPN monitoring draft. Current Yang model (l2nm) does NOT cover the notifications or alarms.

**Comment by oscargdd** [comment]
A priori, according the feedback from the discussions, it seems reasonable to add the limit at vpn_node level. We can do some discussions on the topic. Please comment.

**Comment by sbarguil** [comment]
Max Neighbour Mac address limit IETF-OPSAWG-WG/lxnm#242
