### ISSUE TITLE
how precedence-type is different from access-priority under availability

### ISSUE THREAD

**Issue by billwuqin** [oscargdd/l2nm#5]
I feel the role of access-priority and precedence-type is almost same. what is the their key difference? one is service level, the other is access level? Can you provide a usage example of precedence-type?

**Comment by billwuqin** [comment]
RFC 8466 defines the "access-priority" leaf as a preference for a particular access.  This preference is used to model load-balancing or primary/backup scenarios. Precedence-type defined in L2NM is used to model only primary/back scenarios, I am wondering, whether access-priority in RFC8466 can be reused, probably this question is related common type that can be factored out from both documents.

**Comment by boucadair** [comment]
To check if we can reuse the group defined in the common module

**Comment by billwuqin** [comment]
Here is snippet of svc-precedence and access-priority
                          +--rw svc-precedence
                          |  +--rw precedence?   identityref

                          +--rw availability
                          |  +--rw access-priority?       uint32
                          |  +--rw (redundancy-mode)?
                          |     +--:(single-active)
                          |     |  +--rw single-active?   boolean
                          |     +--:(all-active)
                          |        +--rw all-active?      boolean
  grouping svc-precedence {
    container svc-precedence {
      leaf precedence {
        type identityref {
          base precedence-type;
        }
        description
          "Defining service redundancy in transport
           network.";
      }
      description
        "Transport netowrk precedence selector
         Primary or Secondary tunnel.";
    }
    description
      "Transport netowrk precedence selector
       Primary or Secondary tunnel.";
  }

  identity precedence-type {
    description
      "Redundancy type. The service can be created
       with active and bakcup signalization.";
  }

  identity primary {
    base precedence-type;
    description
      "Identifies the Main L2VPN.";
  }

  identity backup {
    base precedence-type;
    description
      "Identifies the Backup L2VPN.";
  }
In original design of RFC8466, if the access-priority of the network access has the highest value, this network access will be seen as primary network access. Therefore precedence within svc-precedence may be redundant or not needed.

**Comment by billwuqin** [comment]
Yes, group defined in the vpn-common could be resued, and need to harmonized with 
                          +--rw access-diversity {site-diversity}?
                          |  +--rw groups
                          |  |  +--rw fate-sharing-group-size?   uint16
                          |  |  +--rw group-color?               string
                          |  |  +--rw group* [group-id]
                          |  |     +--rw group-id    string
in the L2NM model

**Comment by boucadair** [comment]
> 
> 
> Yes, group defined in the vpn-common could be resued, and need to harmonized with
> +--rw access-diversity {site-diversity}?
> | +--rw groups
> | | +--rw fate-sharing-group-size? uint16
> | | +--rw group-color? string
> | | +--rw group* [group-id]
> | | +--rw group-id string
> in the L2NM model

Please find an update to the common module at: https://github.com/IETF-OPSAWG-WG/l3nm/commit/a8db4bfea5bd6257d1c2799436123aa05cd5fa87

Please review. Thanks.

**Comment by sbarguil** [comment]
how precedence-type is different from access-priority under availability IETF-OPSAWG-WG/lxnm#243
