### ISSUE TITLE
Service mapping with BGP Tunnel and MPLS with LDP 

### ISSUE THREAD

**Issue by billwuqin** [oscargdd/l2nm#6]
Is BGP Tunnel BGP over GRE? Is there any other BGP Tunnel type? In addition, TE service mapping provide service mapping to TE tunnel, but how Service Mapping with BGP tunnel or MPLS with LDP? Where is this specified?

**Comment by oscargdd** [comment]
The mapping is specified in the "transport-encapsulation" container

**Comment by billwuqin** [comment]
Good, I think L2NM focuses on Non-TE part mapping, for TE Service mapping can be addressed in TEAS TE service mapping draft.
Probably the issue ticket
https://github.com/oscargdd/l2nm/issues/12
can address my comments.
Also I am wondering whether non-TE mapping and TE mapping can be clarified somewhere in one document.

**Comment by billwuqin** [comment]
Additional comments, support we support multiple Non-TE tunnels, how do we decide which tunnel should be selected, to address this, I think we should support tunnel auto-select, each tunnel is assigned with different priority. 
In addition do we need to support tunnel stitching feature, in this case, end to end tunnel comprises of multiple tunnels in different domain, each tunnel in different domain can be identified by remote peer address.

**Comment by lmunozm** [comment]
BGP tunnel can refer also to BGP-LU in SMPLS for example

**Comment by lmunozm** [comment]
The "auto select" option can be of help, as a way to make it explicit, but by default (no preference given) you also leave the decision to the IP controller, whatever is set by default at that level.

Regarding TE options, the model should inherit (In my understanding it does, even if not made explicit in the document) the QoS "custom" requirements from LxSM . As an example, the service can require to be optimised in latency, and then the decision on the tunnel binding done by the controller must be consistent with this preference. The service model does not preclude especific binding to tunnels looked at in other standard models, but also allow different ways of implementation.  For this specific case, binding decision can be made by a PCE in the controller (that in turn can allow explicit path binding or dynamic SR Policy implementations), as an example.
RFC8299 Page 15: inside QoS profiel, custom
+--rw latency
             |  |                 |  +--rw (flavor)?
             |  |                 |     +--:(lowest)
             |  |                 |     |  +--rw use-lowest-latency?
             |  |                 |     |          empty
             |  |                 |     +--:(boundary)
             |  |                 |        +--rw latency-boundary?
             |  |                 |                uint16

**Comment by boucadair** [comment]
Check with the service mapping authors
